trigger:
- master

pool:
  name: 'govpool'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'unilever-vbd-private-acr'
    repository: 'nginx-echo-headers'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: 'latest'
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Owaino-ARM-Service-Connection'
    azureResourceGroup: 'unilever-vbd'
    kubernetesCluster: 'unilever-vbd-cluster'
    command: 'apply'
    arguments: '-f deploy.yaml'