trigger:
- master

pool:
  name: 'default'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'unilever-vbd-private-acr'
    repository: 'nginx-echo-headers'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: 'latest'
    
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Owaino-ARM-Service-Connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az --version
      az account set --subscription 4de19e4b-3d22-4e36-9fd7-54b9c225ef52
      az aks get-credentials --resource-group unilever-vbd --name unilever-vbd-cluster
      az account show
- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'azure-devops-sa'
    namespace: 'colors-api'
    command: 'apply'
    arguments: '-f deploy.yaml'

